/**
 * Generated by `php artisan menu:pages` (host entry: `modules:pages`) from
 * the `telegram.modules_frontend_pages` registry (module service providers
 * register their `resources/js/pages` dirs there).
 *
 * Do not edit by hand: keys are rewritten to the canonical "./pages/<name>.tsx"
 * shape so resolvePageComponent matches uniformly across platform and module
 * pages. Re-run `php artisan modules:pages` after changing the registry.
 */
const loaders = {
        ...import.meta.glob('../../misc/BAGArt/tgbot-module-antispam/resources/js/pages/**/*.tsx'),
};

export const modulePageLoaders = Object.fromEntries(
    Object.entries(loaders).map(([path, loader]) => [
        path.replace(/^.*\/resources\/js\/pages\//, './pages/'),
        loader,
    ]),
);
