name: Dependency Review

on:
  pull_request:
    branches:
      - develop
      - main
      - master
      - workos

permissions:
  contents: read

jobs:
  dependency-review:
    uses: BAGArt/telegram-platform-workflows/.github/workflows/dependency-review.yml@eec4b204ccff62e0a9f68d5fdb5581db315947b7 # pin!
