name: Dependency Review

on:
  pull_request:
    branches:
      - develop
      - main
      - master
      - workos

permissions:
  contents: read

jobs:
  dependency-review:
    uses: BAGArt/telegram-platform-workflows/.github/workflows/dependency-review.yml@0cc0f56eacf9e673b76d5e8f6808d7f29c0e53c0 # pin!
