name: Dependency Review

on:
  pull_request:
    branches:
      - develop
      - main
      - master
      - workos

permissions:
  contents: read

jobs:
  dependency-review:
    uses: BAGArt/telegram-platform-workflows/.github/workflows/dependency-review.yml@eae9e6052c176080880935e854d9b60c07a7b007 # pin!
