name: Docker

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:
    paths:
      - 'docker/**'
      - 'Dockerfile*'
      - 'docker-compose*'

permissions:
  contents: read

jobs:
  docker:
    uses: BAGArt/telegram-platform-workflows/.github/workflows/docker.yml@aa5b79def975bad2703df72cdbc12a34a67cc3b1 # pin!
    permissions:
      contents: read
      packages: write # image push on main/master/tags
    with:
      php-version: '8.5'
      push-image: ${{ github.event_name == 'push' }}
