name: Docker

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:
    paths:
      - 'docker/**'
      - 'Dockerfile*'
      - 'docker-compose*'

permissions:
  contents: read

jobs:
  docker:
    uses: BAGArt/telegram-platform-workflows/.github/workflows/docker.yml@262b6fbf75e2d7c0262b13a79c0cb7b8393fac05 # pin!
    permissions:
      contents: read
      packages: write # image push on main/master/tags
    with:
      php-version: '8.5'
      push-image: ${{ github.event_name == 'push' }}
