name: Quality

on:
  push:
    branches:
      - develop
      - main
      - master
      - workos
  pull_request:
    branches:
      - develop
      - main
      - master
      - workos

permissions:
  contents: read

jobs:
  quality:
    uses: BAGArt/telegram-platform-workflows/.github/workflows/lint.yml@9d363fa8e3f6578105b0b3d37bb50713a4f7d58f # pin!
    with:
      php-version: '8.5'
