name: Quality

on:
  push:
    branches:
      - develop
      - main
      - master
      - workos
  pull_request:
    branches:
      - develop
      - main
      - master
      - workos

permissions:
  contents: read

jobs:
  quality:
    uses: BAGArt/telegram-platform-workflows/.github/workflows/lint.yml@262b6fbf75e2d7c0262b13a79c0cb7b8393fac05 # pin!
    with:
      php-version: '8.5'
