name: Quality

on:
  push:
    branches:
      - develop
      - main
      - master
      - workos
  pull_request:
    branches:
      - develop
      - main
      - master
      - workos

permissions:
  contents: read

jobs:
  quality:
    uses: BAGArt/telegram-platform-workflows/.github/workflows/lint.yml@eadb81c9ba237ba15e1c827d69f8f5c837cec051 # pin!
    with:
      php-version: '8.5'
