name: Tests

on:
  push:
    branches:
      - develop
      - main
      - master
      - workos
  pull_request:
    branches:
      - develop
      - main
      - master
      - workos

permissions:
  contents: read

jobs:
  tests:
    uses: BAGArt/telegram-platform-workflows/.github/workflows/tests.yml@e9f2717bc839bca666e8b1cd181e6e0a63252e2d # pin!
    with:
      php-version: '8.5'
