name: Tests

on:
  push:
    branches:
      - develop
      - main
      - master
      - workos
  pull_request:
    branches:
      - develop
      - main
      - master
      - workos

permissions:
  contents: read

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: BAGArt/telegram-platform-workflows/.github/workflows/tests.yml@c13903f617e858d6fe4f724cd9650d49e37e5226 # pin!
    with:
      php-version: '8.5'
