name: Tests

on:
  push:
    branches:
      - develop
      - main
      - master
      - workos
  pull_request:
    branches:
      - develop
      - main
      - master
      - workos

permissions:
  contents: read

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: BAGArt/telegram-platform-workflows/.github/workflows/tests.yml@36856d23c1100f2f6f5ca207ecf018662c57fb1e # pin!
    with:
      php-version: '8.5'
